-- =============================================
-- Script: Agregar campo OBSERVACION_ATENCION
-- Descripción: Agregar columna para separar la observación inicial de la observación de atención
-- Fecha: 2026-02-21
-- =============================================

-- Agregar columna OBSERVACION_ATENCION a la tabla UTD_ATENCIONES
IF NOT EXISTS (
    SELECT 1 
    FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'dbo.UTD_ATENCIONES') 
    AND name = 'OBSERVACION_ATENCION'
)
BEGIN
    ALTER TABLE dbo.UTD_ATENCIONES
    ADD OBSERVACION_ATENCION NVARCHAR(1000) NULL;
    
    PRINT 'Columna OBSERVACION_ATENCION agregada exitosamente.';
END
ELSE
BEGIN
    PRINT 'La columna OBSERVACION_ATENCION ya existe.';
END
GO

-- Actualizar la vista VW_ATENCIONES_DETALLE para incluir el nuevo campo
IF EXISTS (SELECT 1 FROM sys.views WHERE name = 'VW_ATENCIONES_DETALLE')
BEGIN
    DROP VIEW dbo.VW_ATENCIONES_DETALLE;
    PRINT 'Vista VW_ATENCIONES_DETALLE eliminada.';
END
GO

CREATE VIEW dbo.VW_ATENCIONES_DETALLE
AS
SELECT 
    a.ID_ATENCION,
    a.TIPO_DOCUMENTO,
    a.NUMERO_DOCUMENTO,
    a.NOMBRES,
    a.APELLIDOS,
    a.ID_TIPO_TRAMITE,
    tt.NOMBRE_TRAMITE,
    tt.DESCRIPCION AS DESCRIPCION_TRAMITE,
    a.OBSERVACION AS OBSERVACION_INICIAL,
    a.OBSERVACION_ATENCION,
    a.ES_PREFERENCIAL,
    a.ID_TIPO_PREFERENCIAL,
    tp.NOMBRE_TIPO_PREFERENCIAL,
    a.ID_ESTADO_ATENCION,
    ea.NOMBRE_ESTADO,
    ea.ORDEN AS ORDEN_ESTADO,
    a.FECHA_REGISTRO,
    a.FECHA_ACTUALIZACION,
    a.ID_USUARIO_REGISTRO,
    ur.NombreUsuarioUSU AS NOMBRE_USUARIO_REGISTRO,
    a.ID_USUARIO_ACTUALIZA,
    ua.NombreUsuarioUSU AS NOMBRE_USUARIO_ACTUALIZA
FROM dbo.UTD_ATENCIONES a
    INNER JOIN dbo.UTD_TIPO_TRAMITE tt ON a.ID_TIPO_TRAMITE = tt.ID_TIPO_TRAMITE
    LEFT JOIN dbo.UTD_TIPO_PREFERENCIAL tp ON a.ID_TIPO_PREFERENCIAL = tp.ID_TIPO_PREFERENCIAL
    INNER JOIN dbo.UTD_ESTADO_ATENCION ea ON a.ID_ESTADO_ATENCION = ea.ID_ESTADO_ATENCION
    LEFT JOIN dbo.ADM_Usuario ur ON a.ID_USUARIO_REGISTRO = ur.ID_USUARIO
    LEFT JOIN dbo.ADM_Usuario ua ON a.ID_USUARIO_ACTUALIZA = ua.ID_USUARIO;
GO

PRINT 'Vista VW_ATENCIONES_DETALLE actualizada exitosamente.';
GO
