-- =============================================
-- Script: Agregar Tipo de Trabajo y Detalle de Actividad
-- Fecha: 2026-02-27
-- Descripción: Tablas para clasificar el tipo de trabajo y la actividad realizada en cada atención
-- =============================================

-- 1. Tabla de Tipo de Trabajo
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'UTD_TIPO_TRABAJO')
BEGIN
    CREATE TABLE UTD_TIPO_TRABAJO (
        ID_TIPO_TRABAJO INT PRIMARY KEY IDENTITY(1,1),
        NOMBRE_TIPO_TRABAJO VARCHAR(100) NOT NULL,
        DESCRIPCION VARCHAR(500),
        ESTADO BIT NOT NULL DEFAULT 1,
        FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE()
    );
    
    PRINT 'Tabla UTD_TIPO_TRABAJO creada correctamente.';
END
ELSE
BEGIN
    PRINT 'La tabla UTD_TIPO_TRABAJO ya existe.';
END
GO

-- 2. Tabla de Detalle de Actividad
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'UTD_DETALLE_ACTIVIDAD')
BEGIN
    CREATE TABLE UTD_DETALLE_ACTIVIDAD (
        ID_DETALLE_ACTIVIDAD INT PRIMARY KEY IDENTITY(1,1),
        NOMBRE_ACTIVIDAD VARCHAR(200) NOT NULL,
        DESCRIPCION VARCHAR(500),
        ESTADO BIT NOT NULL DEFAULT 1,
        FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE()
    );
    
    PRINT 'Tabla UTD_DETALLE_ACTIVIDAD creada correctamente.';
END
ELSE
BEGIN
    PRINT 'La tabla UTD_DETALLE_ACTIVIDAD ya existe.';
END
GO

-- 3. Insertar datos en UTD_TIPO_TRABAJO
IF NOT EXISTS (SELECT * FROM UTD_TIPO_TRABAJO WHERE NOMBRE_TIPO_TRABAJO = 'PRESENCIAL')
BEGIN
    INSERT INTO UTD_TIPO_TRABAJO (NOMBRE_TIPO_TRABAJO, DESCRIPCION, ESTADO)
    VALUES 
        ('PRESENCIAL', 'TRABAJO REALIZADO EN OFICINA DIGESA', 1),
        ('REMOTO', 'TRABAJO REALIZADO EN CASA', 1),
        ('HORARIO EXTENDIDO', 'REGISTRAR SOLO CORREOS DE 4:31 PM EN ADELANTE', 1);
    
    PRINT 'Datos insertados en UTD_TIPO_TRABAJO.';
END
ELSE
BEGIN
    PRINT 'Los datos de UTD_TIPO_TRABAJO ya existen.';
END
GO

-- 4. Insertar datos en UTD_DETALLE_ACTIVIDAD
IF NOT EXISTS (SELECT * FROM UTD_DETALLE_ACTIVIDAD WHERE NOMBRE_ACTIVIDAD = 'INGRESO DE DOCUMENTOS MINSA O DIGESA')
BEGIN
    INSERT INTO UTD_DETALLE_ACTIVIDAD (NOMBRE_ACTIVIDAD, DESCRIPCION, ESTADO)
    VALUES 
        ('INGRESO DE DOCUMENTOS MINSA O DIGESA', NULL, 1),
        ('INFORMES AL ADMINISTRADO', NULL, 1),
        ('ENTREGA DE DOCUMENTOS', NULL, 1),
        ('ACTIVIDADES DE LA COORDINACIÓN', NULL, 1),
        ('ARCHIVO DE EXPEDIENTES (AS,CS,CLV,OFICIOS,ETC)', NULL, 1),
        ('ATENCIÓN (SSD) EXPEDIENTES DEL ARCHIVO', NULL, 1),
        ('CORREOS INTERNOS', NULL, 1),
        ('RECEPCIÓN DE EXPEDIENTES (AS, CS,CLV, OFICIOS, ETC)', NULL, 1),
        ('REPORTE DE INCONVENIENTES', NULL, 1),
        ('SEGUIMIENTO Y REPORTE DE ESTADO DE TRAMITE', NULL, 1),
        ('DERIVACIONES POR EL SGD', NULL, 1);
    
    PRINT 'Datos insertados en UTD_DETALLE_ACTIVIDAD.';
END
ELSE
BEGIN
    PRINT 'Los datos de UTD_DETALLE_ACTIVIDAD ya existen.';
END
GO

-- 5. Agregar campos a tabla UTD_ATENCIONES
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('UTD_ATENCIONES') AND name = 'ID_TIPO_TRABAJO')
BEGIN
    ALTER TABLE UTD_ATENCIONES
    ADD ID_TIPO_TRABAJO INT NULL;
    
    PRINT 'Columna ID_TIPO_TRABAJO agregada a UTD_ATENCIONES.';
END
ELSE
BEGIN
    PRINT 'La columna ID_TIPO_TRABAJO ya existe en UTD_ATENCIONES.';
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('UTD_ATENCIONES') AND name = 'ID_DETALLE_ACTIVIDAD')
BEGIN
    ALTER TABLE UTD_ATENCIONES
    ADD ID_DETALLE_ACTIVIDAD INT NULL;
    
    PRINT 'Columna ID_DETALLE_ACTIVIDAD agregada a UTD_ATENCIONES.';
END
ELSE
BEGIN
    PRINT 'La columna ID_DETALLE_ACTIVIDAD ya existe en UTD_ATENCIONES.';
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('UTD_ATENCIONES') AND name = 'NUMERO_EXPEDIENTE')
BEGIN
    ALTER TABLE UTD_ATENCIONES
    ADD NUMERO_EXPEDIENTE VARCHAR(50) NULL;
    
    PRINT 'Columna NUMERO_EXPEDIENTE agregada a UTD_ATENCIONES.';
END
ELSE
BEGIN
    PRINT 'La columna NUMERO_EXPEDIENTE ya existe en UTD_ATENCIONES.';
END
GO

-- 6. Agregar Foreign Keys
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_ATENCIONES_TIPO_TRABAJO')
BEGIN
    ALTER TABLE UTD_ATENCIONES
    ADD CONSTRAINT FK_ATENCIONES_TIPO_TRABAJO
    FOREIGN KEY (ID_TIPO_TRABAJO) REFERENCES UTD_TIPO_TRABAJO(ID_TIPO_TRABAJO);
    
    PRINT 'Foreign Key FK_ATENCIONES_TIPO_TRABAJO creada correctamente.';
END
ELSE
BEGIN
    PRINT 'La Foreign Key FK_ATENCIONES_TIPO_TRABAJO ya existe.';
END
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_ATENCIONES_DETALLE_ACTIVIDAD')
BEGIN
    ALTER TABLE UTD_ATENCIONES
    ADD CONSTRAINT FK_ATENCIONES_DETALLE_ACTIVIDAD
    FOREIGN KEY (ID_DETALLE_ACTIVIDAD) REFERENCES UTD_DETALLE_ACTIVIDAD(ID_DETALLE_ACTIVIDAD);
    
    PRINT 'Foreign Key FK_ATENCIONES_DETALLE_ACTIVIDAD creada correctamente.';
END
ELSE
BEGIN
    PRINT 'La Foreign Key FK_ATENCIONES_DETALLE_ACTIVIDAD ya existe.';
END
GO

-- 7. Establecer valor por defecto PRESENCIAL para registros existentes
UPDATE UTD_ATENCIONES
SET ID_TIPO_TRABAJO = (SELECT ID_TIPO_TRABAJO FROM UTD_TIPO_TRABAJO WHERE NOMBRE_TIPO_TRABAJO = 'PRESENCIAL')
WHERE ID_TIPO_TRABAJO IS NULL;

PRINT 'Actualización completada: registros existentes establecidos con TIPO_TRABAJO = PRESENCIAL.';
GO

PRINT '=================================================';
PRINT 'Script ejecutado correctamente.';
PRINT 'Tablas UTD_TIPO_TRABAJO y UTD_DETALLE_ACTIVIDAD creadas.';
PRINT 'Campos ID_TIPO_TRABAJO, ID_DETALLE_ACTIVIDAD y NUMERO_EXPEDIENTE agregados a UTD_ATENCIONES.';
PRINT '=================================================';
